jobs:
  - name: job11
    type: manifest
    steps:
      - GET: image1-test
     # - GET: image2-test
      - GET: image3-test
     # - PUT: image3-test

  - name: job12
    type: manifest
    steps:
      - GET: project1-test
      - PUT: image1-test
      #- PUT: image2-test

  - name: job13
    type: manifest
    steps:
      - GET: image1-test
      - GET: image3-test  
      #- PUT: image2-test
      - GET: project1-test
      - GET: job12
      
 # - name: job14
  #  type: manifest
   # steps:
    #  - GET: job13
     # - GET: job12
      #- GET: job11
      #- PUT: project2-test
      
      


