triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'tesetinwglthtbth12 triifgfuggujythre in yml oekke13ewuh523'
      
  - name: trigger-dv-man
    type: trigger
    source:
      message: 'tesetinwglthtbth12 triifgfuggujythre in yml oekke13ewuh521'
      counter: 1    

